name: AVH Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up ARM GNU Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '11.3.Rel1'
      
      - name: Install Corellium CLI
        run: |
          curl -L https://downloads.corellium.com/cli/linux/latest/corellium > /usr/local/bin/corellium
          chmod +x /usr/local/bin/corellium
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/avh_key
          chmod 600 ~/.ssh/avh_key
          echo "${{ secrets.AVH_SSH_PUBLIC_KEY }}" > ~/.ssh/avh_key.pub
          
      - name: Build
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-avh.cmake
          cmake --build build
          
      - name: Deploy and Test on AVH
        run: |
          corellium login --token ${{ secrets.CORELLIUM_API_TOKEN }}
          corellium instance create --project ${{ secrets.CORELLIUM_PROJECT_ID }} --flavor arm-virt --os corellium-linux-dev
          corellium instance wait-ready
          corellium instance upload build/${PROJECT_NAME} /root/
          corellium instance exec "chmod +x /root/${PROJECT_NAME} && /root/${PROJECT_NAME}"
        env:
          CORELLIUM_API_TOKEN: ${{ secrets.CORELLIUM_API_TOKEN }}
          CORELLIUM_PROJECT_ID: ${{ secrets.CORELLIUM_PROJECT_ID }}
