name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Adding ARM architecture support..."
          sudo dpkg --add-architecture armhf || {
            echo "Failed to add ARM architecture. Check permissions and dpkg configuration.";
            dpkg --print-architecture;
            dpkg --print-foreign-architectures;
            exit 1;
          }
          
          echo "Configuring package sources..."
          # Backup original sources
          sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
          
          # Create separate sources for ARM
          sudo tee /etc/apt/sources.list.d/armhf.list > /dev/null << 'EOF'
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted universe multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse
          EOF
          
          # Keep original sources for amd64
          sudo sed -i 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list
          
          echo "Updating package lists..."
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update -o Acquire::Check-Valid-Until=false || {
            echo "Failed to update package lists. Verify network connectivity and sources configuration.";
            cat /etc/apt/sources.list;
            cat /etc/apt/sources.list.d/armhf.list;
            exit 1;
          }
          
          echo "Installing all dependencies..."
          sudo apt-get install -y \
            cmake make gcc sshpass netcat-openbsd \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
            libc6:armhf libstdc++6:armhf || {
              echo "Failed to install dependencies. Verify sources and network connectivity.";
              apt-cache policy gcc-arm-linux-gnueabihf;
              exit 1;
          }
          
          echo "Setting up toolchain paths..."
          TOOLCHAIN_PATHS=(
            "/usr/bin"
            "/usr/local/bin"
            "/usr/arm-linux-gnueabihf/bin"
          )
          
          for path in "${TOOLCHAIN_PATHS[@]}"; do
            if [ -f "$path/arm-linux-gnueabihf-gcc" ]; then
              export PATH="$path:$PATH"
              echo "Added toolchain path: $path"
              break
            fi
          done
          
          echo "Verifying toolchain installation..."
          if ! which arm-linux-gnueabihf-gcc; then
            echo "Error: ARM GCC not found in PATH";
            echo "Current PATH: $PATH";
            echo "Looking for ARM toolchain files:";
            sudo find / -name "arm-linux-gnueabihf-gcc" 2>/dev/null || true;
            exit 1;
          fi
          
          echo "ARM toolchain version:"
          arm-linux-gnueabihf-gcc --version || {
            echo "Failed to get toolchain version. Checking installation:";
            dpkg -l | grep -i arm;
            exit 1;
          }
          
          echo "Checking ARM library dependencies:"
          dpkg -l | grep "armhf" || {
            echo "No ARM libraries found. Checking package status:";
            apt-cache policy libc6:armhf libstdc++6:armhf;
            exit 1;
          }

      - name: Verify Environment
        run: |
          echo "Checking ARM toolchain..."
          which arm-linux-gnueabihf-gcc || { echo "ARM GCC not found"; exit 1; }
          arm-linux-gnueabihf-gcc --version
          
          echo "Checking toolchain directory..."
          ls -la toolchains/
          
          echo "Verifying toolchain file contents..."
          cat toolchains/arm-toolchain.cmake
          
          echo "Checking source files..."
          ls -la src/

      - name: Setup Build Environment
        run: |
          echo "Installing ARM build dependencies..."
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo apt-get install -y libc6-dev-armhf-cross linux-libc-dev-armhf-cross
          
          echo "Verifying ARM toolchain..."
          arm-linux-gnueabihf-gcc --version
          arm-linux-gnueabihf-g++ --version
          
          echo "Verifying source files..."
          ls -la src/
          cat src/main.c

      - name: Build
        run: |
          echo "Setting up build directory..."
          rm -rf build
          mkdir -p build
          cd build
          
          echo "Running CMake with ARM toolchain..."
          VERBOSE=1 cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-toolchain.cmake \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_VERBOSE_MAKEFILE=ON \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 2>&1 | tee cmake.log
          CMAKE_EXIT=$?
          
          echo "CMake logs:"
          cat cmake.log
          if [ -f CMakeFiles/CMakeError.log ]; then
            echo "\nCMakeError.log:"
            cat CMakeFiles/CMakeError.log
          fi
          if [ -f CMakeFiles/CMakeOutput.log ]; then
            echo "\nCMakeOutput.log:"
            cat CMakeFiles/CMakeOutput.log
          fi
          
          if [ $CMAKE_EXIT -ne 0 ]; then
            echo "CMake configuration failed"
            exit 1
          fi
          
          echo "\nCMake configuration details:"
          cmake -LA .
          
          echo "\nBuilding project..."
          VERBOSE=1 make 2>&1 | tee make.log
          MAKE_EXIT=${PIPESTATUS[0]}
          
          echo "Make logs:"
          cat make.log
          
          if [ $MAKE_EXIT -ne 0 ]; then
            echo "Build failed"
            exit 1
          fi
          
          echo "\nBuild directory structure:"
          find . -type f -exec ls -lh {} \;
          
          echo "\nVerifying blink binary:"
          if [ ! -f blink ]; then
            echo "Error: blink binary not found!"
            echo "Contents of current directory:"
            ls -la
            echo "\nContents of all build subdirectories:"
            find . -type f -name "blink" -o -name "*.o" -o -name "*.a"
            exit 1
          fi
          
          echo "\nBinary details:"
          file ./blink
          
          echo "\nBinary size:"
          ls -lh ./blink
          
          echo "\nVerifying ARM architecture:"
          arm-linux-gnueabihf-readelf -h ./blink | tee readelf.log
          grep -q "Machine:.*ARM" readelf.log || { echo "Error: Binary is not for ARM architecture"; exit 1; }
          
          echo "\nBinary symbols:"
          arm-linux-gnueabihf-nm ./blink | grep -w 'main'
          
          echo "Build directory contents:"
          ls -la
          
          if [ ! -f blink ]; then
            echo "Error: Build step did not produce the 'blink' binary."
            echo "CMake error log:"
            cat CMakeFiles/CMakeError.log || true
            echo "CMake output log:"
            cat CMakeFiles/CMakeOutput.log || true
            exit 1
          fi
          
          echo "Binary information:"
          file blink
          readelf -h blink || true
          ldd blink || true
          
          echo "Verifying binary architecture:"
          if ! file blink | grep -q "ARM"; then
            echo "Error: Binary is not compiled for ARM"
            exit 1
          fi

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          # Create minimal SSH config for StrictHostKeyChecking
          cat > ~/.ssh/config << 'EOF'
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            LogLevel DEBUG3
          EOF
          chmod 600 ~/.ssh/config
          
          # Set up variables
          PROXY="3ac4e20f-02f4-45bb-bfbd-9f6e3029f981@proxy.app.avh.corellium.com"
          TARGET="pi@10.11.0.1"
          
          # Install expect
          sudo apt-get update && sudo apt-get install -y expect
          
          # Create SSH key copy script
          cat > copy_key.exp << 'EOF'
          #!/usr/bin/expect -f
          set timeout 30
          set proxy [lindex $argv 0]
          set target [lindex $argv 1]
          set key [lindex $argv 2]
          
          spawn bash -c "echo $key | ssh -o ConnectTimeout=10 -J $proxy $target 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys'"
          expect {
            -re ".*password:" { send "raspberry\r"; exp_continue }
            timeout { exit 1 }
            eof { exit [lindex [wait] 3] }
          }
          EOF
          
          chmod +x copy_key.exp
          
          # Copy SSH key using expect script
          echo "Copying SSH key to target..."
          KEY=$(cat ~/.ssh/id_rsa.pub)
          ./copy_key.exp "$PROXY" "$TARGET" "$KEY"
          
          # Test SSH connection with key auth
          echo "Testing SSH connection..."
          if ! ssh -o ConnectTimeout=10 -v -J $PROXY $TARGET 'whoami && echo "SSH_CONNECTION=$SSH_CONNECTION"'; then
            echo "SSH connection failed"
            exit 1
          fi

      - name: Verify Build Output
        run: |
          echo "Verifying blink binary..."
          if [ ! -f "build/blink" ]; then
            echo "Error: build/blink binary not found!"
            echo "Build directory contents:"
            find build -type f -exec ls -l {} \;
            exit 1
          fi
          
          echo "Binary details:"
          file build/blink
          
          echo "Binary architecture:"
          arm-linux-gnueabihf-readelf -A build/blink || true
          
          echo "Binary dependencies:"
          arm-linux-gnueabihf-readelf -d build/blink || true
          
          echo "Binary symbols:"
          arm-linux-gnueabihf-nm build/blink || true
          
          echo "Binary size:"
          arm-linux-gnueabihf-size build/blink || true

      - name: Wait for Device and Configure SSH
        run: |
          PROXY="3ac4e20f-02f4-45bb-bfbd-9f6e3029f981@proxy.app.avh.corellium.com"
          TARGET="pi@10.11.0.1"
          
          # Create SSH config
          mkdir -p ~/.ssh
          cat > ~/.ssh/config << EOF
          Host proxy
            HostName proxy.app.avh.corellium.com
            User 3ac4e20f-02f4-45bb-bfbd-9f6e3029f981
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ServerAliveInterval 30
            ServerAliveCountMax 3
            ConnectTimeout 10
          
          Host target
            HostName 10.11.0.1
            User pi
            ProxyJump proxy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ServerAliveInterval 30
            ServerAliveCountMax 3
            ConnectTimeout 10
          EOF
          
          chmod 600 ~/.ssh/config
          
          # Wait for device to be available (up to 5 minutes)
          echo "Waiting for device to be available..."
          for i in {1..30}; do
            if ssh -q target 'exit 0' 2>/dev/null; then
              echo "Device is available!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Timeout waiting for device"
              exit 1
            fi
            echo "Attempt $i/30: Device not ready, waiting 10 seconds..."
            sleep 10
          done
          
          echo "Testing SSH connection..."
          if ! ssh -v target 'whoami && echo "SSH_CONNECTION=$SSH_CONNECTION"'; then
            echo "SSH connection failed"
            exit 1
          fi

      - name: Setup Target Environment
        run: |
          function retry_command {
            local max_attempts=3
            local delay=10
            local attempt=1
            
            while true; do
              echo "Attempt $attempt/$max_attempts: $1"
              if eval "$2"; then
                return 0
              fi
              
              attempt=$((attempt + 1))
              if [ $attempt -gt $max_attempts ]; then
                echo "Failed after $max_attempts attempts"
                return 1
              fi
              
              echo "Command failed, retrying in $delay seconds..."
              sleep $delay
            done
          }
          
          echo "Creating and fixing permissions for target directory..."
          retry_command "Setting up app directory" 'ssh target "sudo rm -rf /home/pi/app && sudo mkdir -p /home/pi/app && sudo chown -R pi:pi /home/pi/app && sudo chmod -R 755 /home/pi/app"'
          
          echo "Setting up GPIO directory..."
          retry_command "Setting up GPIO directory" 'ssh target "sudo mkdir -p /sys/class/gpio && sudo chmod -R 777 /sys/class/gpio"'
          
          echo "Checking target environment:"
          retry_command "Verifying directories" 'ssh target "ls -ld /home/pi/app && ls -ld /sys/class/gpio"'

      - name: Deploy and Verify
        run: |
          function retry_command {
            local max_attempts=3
            local delay=10
            local attempt=1
            
            while true; do
              echo "Attempt $attempt/$max_attempts: $1"
              if eval "$2"; then
                return 0
              fi
              
              attempt=$((attempt + 1))
              if [ $attempt -gt $max_attempts ]; then
                echo "Failed after $max_attempts attempts"
                return 1
              fi
              
              echo "Command failed, retrying in $delay seconds..."
              sleep $delay
            done
          }
          
          if [ ! -f build/blink ]; then
            echo "Error: blink binary not found in build directory!"
            echo "Build directory contents:"
            ls -la build/
            exit 1
          fi
          
          echo "Creating app directory on target..."
          retry_command "Creating directory" 'ssh target "sudo mkdir -p /home/pi/app && sudo chown pi:pi /home/pi/app"'
          
          echo "Installing dependencies on target..."
          retry_command "Installing deps" 'ssh target "sudo apt-get update && \
            sudo apt-get install -y build-essential gcc g++ libc6 libstdc++6 && \
            sudo ldconfig"'
          
          echo "Deploying blink binary..."
          retry_command "Copying binary" 'scp -v build/blink target:/home/pi/app/'
          
          echo "Setting executable permissions..."
          retry_command "Setting permissions" 'ssh target "chmod +x /home/pi/app/blink"'
          
          echo "Verifying binary on target:"
          retry_command "Checking binary" 'ssh target "ls -lh /home/pi/app/blink"'
          
          echo "Checking binary format:"
          retry_command "Checking format" 'ssh target "file /home/pi/app/blink"'
          
          echo "Checking target system:"
          retry_command "System info" 'ssh target "uname -a && cat /proc/cpuinfo | grep -i model"'
          
          echo "Checking binary dependencies:"
          retry_command "Checking deps" 'ssh target "ldd /home/pi/app/blink || { echo \"Error: Missing dependencies\"; exit 1; }"'
          
          echo "Checking GPIO access:"
          retry_command "GPIO check" 'ssh target "sudo ls -l /sys/class/gpio/ && groups pi"'
          
          echo "Running blink program:"
          retry_command "Executing binary" 'ssh target "cd /home/pi/app && \
            sudo bash -c \"export LD_LIBRARY_PATH=/lib:/usr/lib:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu && \
            /home/pi/app/blink\""'
