name: Build and Deploy ARM IoT Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          arm-none-eabi-gcc --version
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      
      - name: Package Build
        run: |
          tar -czf build.tar.gz build/
          echo "Build artifacts created successfully"
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          echo "Host proxy.app.avh.corellium.com
            User claynelson
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          ssh -v proxy.app.avh.corellium.com 'echo "Proxy connection successful"'
      
      - name: Deploy to AVH
        run: |
          ssh -J proxy.app.avh.corellium.com pi@10.11.0.1 'mkdir -p ~/app'
          scp -o ProxyJump=proxy.app.avh.corellium.com build/blink pi@10.11.0.1:~/app/
          ssh -J proxy.app.avh.corellium.com pi@10.11.0.1 'chmod +x ~/app/blink && ~/app/blink'
