name: Build and Deploy ARM IoT Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          arm-none-eabi-gcc --version
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      
      - name: Package Build
        run: |
          tar -czf build.tar.gz build/
          echo "Build artifacts created successfully"
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzXCQc2nBGJ+aRw5/7QNlv+IvNCi4PR56V+TfyVctBcitex5iHOdCsOWlMOwPkOqornQJXD7ls6SjBmRclu2Kq43kWofP8i+H4fzGp7vtXlKYMAYs7JPQjp/03VmsBq1WN0G3IcG0if+FbivXGP3+DW/jSWqlkZS6b590naamqA8NiQhaSaBRx/pDNp+VB1OZEYt1TIIdzMUo8MMYKx94PVVA/k+iKcb0fYP7I9DoaFS42iANg1O6boahzv0P729pYJqXzERrVPxh+x5GWK/ZIqnseXrVSudiFUADBvtqeDbsx2Ld2yKFDOLMoXG4dBtplX0HDJmM0p/5+gl2DS1n3a+rl1mrsbLXytAxzzaRBUI+QiNG/1L8pBdk8ZXI3ziuKOXj09Bw6RuZWIlvz0Ex7UeZEoYN4RxOeDYGxLOyqNQX1xQ4yVSE0e+lze4Q7e0PL+fe2GOxdmugQlZYsQ2U4ZdO19n1+kbuGgo8ggfYV/rNVwJkG2pmcM70Bw3RhjVrl12N0ZafJTypbWgRYStkOi42iYhctPfAF2wDHZJ0lQaWZgOURghip6SrfscxV/ufVVfByUhVJEta2yjLBsZl0yZf+yCa07DTVYS7d0337R5vGUnlIKwWGyVPZ8TreBGxULMB3DJGoSpXQVmcU9t2S/BYqfjB12U+aWOxbCZuNtQ== claynelson@clays-laptop-5.lan" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            LogLevel DEBUG3

          Host proxy
            HostName proxy.app.avh.corellium.com
            User claynelson
            IdentityFile ~/.ssh/id_rsa
            
          Host target
            HostName 10.11.0.1
            User pi
            ProxyJump proxy" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          ssh-keygen -l -f ~/.ssh/id_rsa.pub
          
          ssh -v proxy 'echo "Proxy connection successful"'
      
      - name: Deploy to AVH
        run: |
          ssh target 'mkdir -p ~/app'
          scp build/blink target:~/app/
          ssh target 'chmod +x ~/app/blink && ~/app/blink'
