name: AVH Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          arm-none-eabi-gcc --version
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.AVH_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          
      - name: Build
        run: |
          make -f Makefile.arm
          
      - name: Deploy and Test on AVH
        run: |
          ssh -o StrictHostKeyChecking=no -J ${{ secrets.AVH_USER }}@proxy.app.avh.corellium.com pi@10.11.0.1 'mkdir -p ~/app'
          scp -o StrictHostKeyChecking=no -J ${{ secrets.AVH_USER }}@proxy.app.avh.corellium.com build/blink pi@10.11.0.1:~/app/
          ssh -o StrictHostKeyChecking=no -J ${{ secrets.AVH_USER }}@proxy.app.avh.corellium.com pi@10.11.0.1 'chmod +x ~/app/blink && ~/app/blink'
        env:
          AVH_SSH_PRIVATE_KEY: ${{ secrets.AVH_SSH_PRIVATE_KEY }}
          AVH_SSH_PUBLIC_KEY: ${{ secrets.AVH_SSH_PUBLIC_KEY }}
          AVH_USER: ${{ secrets.AVH_USER }}
