name: Build and Deploy ARM IoT Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          arm-none-eabi-gcc --version
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      
      - name: Package Build
        run: |
          tar -czf build.tar.gz build/
          echo "Build artifacts created successfully"
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Generate a new SSH key pair
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          
          # Show the public key - you'll need to add this to your avh.yml
          echo "New public key to add to avh.yml:"
          cat ~/.ssh/id_rsa.pub
          
          # Configure SSH
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            LogLevel DEBUG3

          Host proxy
            HostName proxy.app.avh.corellium.com
            User claynelson
            IdentityFile ~/.ssh/id_rsa
            
          Host target
            HostName 10.11.0.1
            User pi
            ProxyJump proxy" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          # Show key fingerprint
          ssh-keygen -l -f ~/.ssh/id_rsa.pub
          
          # Test proxy connection
          ssh -v proxy 'echo "Proxy connection successful"'
      
      - name: Deploy to AVH
        run: |
          ssh target 'mkdir -p ~/app'
          scp build/blink target:~/app/
          ssh target 'chmod +x ~/app/blink && ~/app/blink'
