name: AVH Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AVH_USER: ${{ secrets.AVH_USER }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          arm-none-eabi-gcc --version
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.AVH_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          ssh-keyscan -H proxy.app.avh.corellium.com >> ~/.ssh/known_hosts
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      
      - name: Deploy to AVH
        run: |
          if [ -z "$AVH_USER" ]; then
            echo "Error: AVH_USER is not set"
            exit 1
          fi
          PROXY="${AVH_USER}@proxy.app.avh.corellium.com"
          TARGET="pi@10.11.0.1"
          
          echo "Creating app directory..."
          ssh -o StrictHostKeyChecking=no -J "$PROXY" "$TARGET" 'mkdir -p ~/app'
          
          echo "Copying binary..."
          scp -o StrictHostKeyChecking=no -J "$PROXY" build/blink "$TARGET:~/app/"
          
          echo "Running application..."
          ssh -o StrictHostKeyChecking=no -J "$PROXY" "$TARGET" 'chmod +x ~/app/blink && ~/app/blink'
