name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Add ARM architecture
          sudo dpkg --add-architecture armhf
          
          # Backup and create new sources.list
          sudo mv /etc/apt/sources.list /etc/apt/sources.list.bak
          sudo tee /etc/apt/sources.list > /dev/null << 'EOF'
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
          
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted universe multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse
          EOF
          
          # Update and install dependencies
          sudo apt-get update
          sudo apt-get install -y cmake make gcc sshpass
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          
          # Verify toolchain installation
          arm-linux-gnueabihf-gcc --version

      - name: Build
        run: |
          echo "Creating build directory..."
          mkdir -p build
          cd build
          
          echo "Checking toolchain file..."
          if [ ! -f ../toolchains/arm-toolchain.cmake ]; then
            echo "Error: Toolchain file not found"
            exit 1
          fi
          cat ../toolchains/arm-toolchain.cmake
          
          echo "Running CMake with ARM toolchain..."
          CFLAGS="-march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8" \
          CXXFLAGS="-march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8" \
          LDFLAGS="-march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8" \
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-toolchain.cmake \
                -DCMAKE_C_FLAGS="-march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8" \
                -DCMAKE_CXX_FLAGS="-march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8" \
                -DCMAKE_EXE_LINKER_FLAGS="-march=armv8-a -mfloat-abi=hard -mfpu=neon-fp-armv8" ..
          
          echo "CMake cache contents:"
          cat CMakeCache.txt
          
          echo "Running Make..."
          make VERBOSE=1
          
          echo "Build directory contents:"
          ls -la
          
          if [ ! -f blink ]; then
            echo "Error: Build step did not produce the 'blink' binary."
            echo "Checking CMake error log:"
            cat CMakeFiles/CMakeError.log || true
            exit 1
          fi
          
          echo "Checking binary type:"
          file blink
          readelf -h blink || true

      - name: Configure SSH
        run: |
          # Create SSH directory and set permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Write private key and set permissions
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Generate public key
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          
          # Create SSH config with enhanced settings
          cat > ~/.ssh/config << 'EOF'
          Host proxy
            HostName proxy.app.avh.corellium.com
            Port 22
            User 3ac4e20f-02f4-45bb-bfbd-9f6e3029f981
            IdentityFile ~/.ssh/id_rsa
            PreferredAuthentications publickey
            PubkeyAcceptedKeyTypes +ssh-rsa
            HostKeyAlgorithms +ssh-rsa
            KexAlgorithms +diffie-hellman-group14-sha1
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            LogLevel DEBUG3
            ServerAliveInterval 30
            ServerAliveCountMax 3
            ConnectTimeout 30
            LocalForward 2222 10.11.0.1:22

          Host target
            HostName localhost
            Port 2222
            User pi
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            LogLevel DEBUG3
            ServerAliveInterval 30
            ServerAliveCountMax 3
            ConnectTimeout 30
          EOF
          chmod 600 ~/.ssh/config
          
          # Test SSH connection with debugging
          echo "Testing SSH connection to proxy..."
          ssh -v proxy echo "SSH connection successful!" || echo "SSH connection failed"

      - name: Deploy to AVH
        run: |
          echo "Deploying blink binary to AVH..."
          
          echo "Build directory contents:"
          ls -la build/
          
          echo "Network configuration:"
          netstat -nr
          ip route || true
          
          echo "DNS resolution:"
          dig +short proxy.app.avh.corellium.com || true
          nslookup proxy.app.avh.corellium.com || true
          
          echo "Testing proxy connectivity:"
          for port in 22 2003 2222; do
            echo "Testing port $port..."
            nc -zv proxy.app.avh.corellium.com $port || true
          done
          
          echo "SSH debug information:"
          ssh -vvv proxy echo "SSH connection test" || true
          
          echo "SSH key information:"
          ssh-keygen -l -f ~/.ssh/id_rsa
          echo "Public key contents:"
          cat ~/.ssh/id_rsa.pub
          
          echo "SSH config:"
          cat ~/.ssh/config
          
          # Set up port forwarding tunnel
          echo "Setting up port forwarding tunnel..."
          ssh -f -N proxy
          sleep 5
          
          # Test connection through tunnel
          echo "Testing connection through tunnel..."
          if ! ssh -v target echo "SSH connection successful!"; then
            echo "Failed to connect through tunnel. Trying direct connection..."
            if ! ssh -v proxy echo "Direct SSH connection successful!"; then
              echo "All connection attempts failed."
              exit 1
            fi
          fi
          
          # Test target connectivity
          echo "Testing target connectivity..."
          if ! ssh -v target echo "Target reachable"; then
            echo "Failed to connect to target device."
            exit 1
          fi
          
          # Attempt deployment
          echo "Copying binary to target..."
          if ! scp -v build/blink target:~/; then
            echo "Failed to copy binary."
            exit 1
          fi
          
          echo "Setting permissions and running binary..."
          if ! ssh -v target "chmod +x ~/blink && ~/blink"; then
            echo "Failed to execute binary on target."
            exit 1
          fi
