name: Build and Deploy ARM IoT Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi sshpass
          arm-none-eabi-gcc --version
      
      - name: Build
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing repository contents:"
          ls -la
          
          echo "\nCreating build directory..."
          mkdir -p build
          cd build
          
          echo "\nRunning CMake..."
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON ..
          
          echo "\nRunning Make..."
          make VERBOSE=1
          
          echo "\nChecking build output:"
          ls -la
          
          if [ ! -f blink ]; then
            echo "Error: Build step did not produce the 'blink' binary."
            exit 1
          fi
          
          echo "\nBuild successful! Binary details:"
          file blink
      
      - name: Package Build
        run: |
          tar -czf build.tar.gz build/
          echo "Build artifacts created successfully"
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Generate public key with modern format
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          
      - name: Configure SSH
        run: |
          cat > ~/.ssh/config << 'EOF'
          Host proxy
            HostName proxy.app.avh.corellium.com
            User 3ac4e20f-02f4-45bb-bfbd-9f6e3029f981
            IdentityFile ~/.ssh/id_rsa
            PreferredAuthentications publickey
            PubkeyAcceptedKeyTypes rsa-sha2-512,rsa-sha2-256,ssh-rsa
            HostKeyAlgorithms ecdsa-sha2-nistp256
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null

          Host target
            HostName 10.11.0.1
            User pi
            ProxyCommand ssh proxy -W %h:%p
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          EOF
          chmod 600 ~/.ssh/config
          
          # Test connection
          echo "\nTesting connection to target..."
          sshpass -p 'raspberry' ssh -v target 'echo Connected to target'
      
      - name: Deploy to AVH
        run: |
          # Verify build artifact exists
          if [ ! -f build/blink ]; then
            echo "Error: build/blink does not exist"
            exit 1
          fi
          
          echo "Creating app directory..."
          sshpass -p 'raspberry' ssh -v target 'mkdir -p ~/app'
          
          echo "\nVerifying directory creation..."
          sshpass -p 'raspberry' ssh -v target 'ls -la ~/app'
          
          echo "\nCopying binary..."
          sshpass -p 'raspberry' scp -v -F ~/.ssh/config build/blink target:~/app/
          
          echo "\nVerifying file copy..."
          sshpass -p 'raspberry' ssh -v target 'ls -la ~/app/blink'
          
          echo "\nSetting permissions..."
          sshpass -p 'raspberry' ssh -v target 'chmod +x ~/app/blink'
          
          echo "\nVerifying permissions..."
          sshpass -p 'raspberry' ssh -v target 'ls -la ~/app/blink'
          
          echo "\nExecuting binary..."
          sshpass -p 'raspberry' ssh -v target '~/app/blink'
